package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Airline generated by hbm2java
 */
@Entity
@Table(name = "airline", catalog = "airportdb", uniqueConstraints = @UniqueConstraint(columnNames = "iata"))
public class Airline implements java.io.Serializable {

	private Short airlineId;
	private Airport airport;
	private String iata;
	private String airlinename;
	private Set<Flightschedule> flightschedules = new HashSet<Flightschedule>(0);
	private Set<Flight> flights = new HashSet<Flight>(0);

	public Airline() {
	}

	public Airline(Airport airport, String iata) {
		this.airport = airport;
		this.iata = iata;
	}

	public Airline(Airport airport, String iata, String airlinename, Set<Flightschedule> flightschedules,
			Set<Flight> flights) {
		this.airport = airport;
		this.iata = iata;
		this.airlinename = airlinename;
		this.flightschedules = flightschedules;
		this.flights = flights;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "airline_id", unique = true, nullable = false)
	public Short getAirlineId() {
		return this.airlineId;
	}

	public void setAirlineId(Short airlineId) {
		this.airlineId = airlineId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "base_airport", nullable = false)
	public Airport getAirport() {
		return this.airport;
	}

	public void setAirport(Airport airport) {
		this.airport = airport;
	}

	@Column(name = "iata", unique = true, nullable = false, length = 2)
	public String getIata() {
		return this.iata;
	}

	public void setIata(String iata) {
		this.iata = iata;
	}

	@Column(name = "airlinename", length = 30)
	public String getAirlinename() {
		return this.airlinename;
	}

	public void setAirlinename(String airlinename) {
		this.airlinename = airlinename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airline")
	public Set<Flightschedule> getFlightschedules() {
		return this.flightschedules;
	}

	public void setFlightschedules(Set<Flightschedule> flightschedules) {
		this.flightschedules = flightschedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airline")
	public Set<Flight> getFlights() {
		return this.flights;
	}

	public void setFlights(Set<Flight> flights) {
		this.flights = flights;
	}

}
