package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Arrays;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AirportGeoId generated by hbm2java
 */
@Embeddable
public class AirportGeoId implements java.io.Serializable {

	private short airportId;
	private String name;
	private String city;
	private String country;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private byte[] geolocation;

	public AirportGeoId() {
	}

	public AirportGeoId(short airportId, String name, BigDecimal latitude, BigDecimal longitude, byte[] geolocation) {
		this.airportId = airportId;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.geolocation = geolocation;
	}

	public AirportGeoId(short airportId, String name, String city, String country, BigDecimal latitude,
			BigDecimal longitude, byte[] geolocation) {
		this.airportId = airportId;
		this.name = name;
		this.city = city;
		this.country = country;
		this.latitude = latitude;
		this.longitude = longitude;
		this.geolocation = geolocation;
	}

	@Column(name = "airport_id", nullable = false)
	public short getAirportId() {
		return this.airportId;
	}

	public void setAirportId(short airportId) {
		this.airportId = airportId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "latitude", nullable = false, precision = 11, scale = 8)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 11, scale = 8)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "geolocation", nullable = false)
	public byte[] getGeolocation() {
		return this.geolocation;
	}

	public void setGeolocation(byte[] geolocation) {
		this.geolocation = geolocation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AirportGeoId))
			return false;
		AirportGeoId castOther = (AirportGeoId) other;

		return (this.getAirportId() == castOther.getAirportId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this.getLatitude() != null
						&& castOther.getLatitude() != null && this.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this.getLongitude() != null
						&& castOther.getLongitude() != null && this.getLongitude().equals(castOther.getLongitude())))
				&& ((this.getGeolocation() == castOther.getGeolocation())
						|| (this.getGeolocation() != null && castOther.getGeolocation() != null
								&& Arrays.equals(this.getGeolocation(), castOther.getGeolocation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAirportId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result + (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		result = 37 * result + (getGeolocation() == null ? 0 : Arrays.hashCode(this.getGeolocation()));
		return result;
	}

}
