package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Airplane generated by hbm2java
 */
@Entity
@Table(name = "airplane", catalog = "airportdb")
public class Airplane implements java.io.Serializable {

	private Integer airplaneId;
	private int capacity;
	private int typeId;
	private int airlineId;
	private Set<Flight> flights = new HashSet<Flight>(0);

	public Airplane() {
	}

	public Airplane(int capacity, int typeId, int airlineId) {
		this.capacity = capacity;
		this.typeId = typeId;
		this.airlineId = airlineId;
	}

	public Airplane(int capacity, int typeId, int airlineId, Set<Flight> flights) {
		this.capacity = capacity;
		this.typeId = typeId;
		this.airlineId = airlineId;
		this.flights = flights;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "airplane_id", unique = true, nullable = false)
	public Integer getAirplaneId() {
		return this.airplaneId;
	}

	public void setAirplaneId(Integer airplaneId) {
		this.airplaneId = airplaneId;
	}

	@Column(name = "capacity", nullable = false)
	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	@Column(name = "type_id", nullable = false)
	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	@Column(name = "airline_id", nullable = false)
	public int getAirlineId() {
		return this.airlineId;
	}

	public void setAirlineId(int airlineId) {
		this.airlineId = airlineId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airplane")
	public Set<Flight> getFlights() {
		return this.flights;
	}

	public void setFlights(Set<Flight> flights) {
		this.flights = flights;
	}

}
