package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Airport generated by hbm2java
 */
@Entity
@Table(name = "airport", catalog = "airportdb", uniqueConstraints = @UniqueConstraint(columnNames = "icao"))
public class Airport implements java.io.Serializable {

	private Short airportId;
	private String iata;
	private String icao;
	private String name;
	private Set<Airline> airlines = new HashSet<Airline>(0);
	private Set<Flight> flightsForTo = new HashSet<Flight>(0);
	private Set<Flight> flightsForFrom = new HashSet<Flight>(0);
	private Set<Flightschedule> flightschedulesForTo = new HashSet<Flightschedule>(0);
	private Set<Flightschedule> flightschedulesForFrom = new HashSet<Flightschedule>(0);

	public Airport() {
	}

	public Airport(String icao, String name) {
		this.icao = icao;
		this.name = name;
	}

	public Airport(String iata, String icao, String name, Set<Airline> airlines, Set<Flight> flightsForTo,
			Set<Flight> flightsForFrom, Set<Flightschedule> flightschedulesForTo,
			Set<Flightschedule> flightschedulesForFrom) {
		this.iata = iata;
		this.icao = icao;
		this.name = name;
		this.airlines = airlines;
		this.flightsForTo = flightsForTo;
		this.flightsForFrom = flightsForFrom;
		this.flightschedulesForTo = flightschedulesForTo;
		this.flightschedulesForFrom = flightschedulesForFrom;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "airport_id", unique = true, nullable = false)
	public Short getAirportId() {
		return this.airportId;
	}

	public void setAirportId(Short airportId) {
		this.airportId = airportId;
	}

	@Column(name = "iata", length = 3)
	public String getIata() {
		return this.iata;
	}

	public void setIata(String iata) {
		this.iata = iata;
	}

	@Column(name = "icao", unique = true, nullable = false, length = 4)
	public String getIcao() {
		return this.icao;
	}

	public void setIcao(String icao) {
		this.icao = icao;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airport")
	public Set<Airline> getAirlines() {
		return this.airlines;
	}

	public void setAirlines(Set<Airline> airlines) {
		this.airlines = airlines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airportByTo")
	public Set<Flight> getFlightsForTo() {
		return this.flightsForTo;
	}

	public void setFlightsForTo(Set<Flight> flightsForTo) {
		this.flightsForTo = flightsForTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airportByFrom")
	public Set<Flight> getFlightsForFrom() {
		return this.flightsForFrom;
	}

	public void setFlightsForFrom(Set<Flight> flightsForFrom) {
		this.flightsForFrom = flightsForFrom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airportByTo")
	public Set<Flightschedule> getFlightschedulesForTo() {
		return this.flightschedulesForTo;
	}

	public void setFlightschedulesForTo(Set<Flightschedule> flightschedulesForTo) {
		this.flightschedulesForTo = flightschedulesForTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "airportByFrom")
	public Set<Flightschedule> getFlightschedulesForFrom() {
		return this.flightschedulesForFrom;
	}

	public void setFlightschedulesForFrom(Set<Flightschedule> flightschedulesForFrom) {
		this.flightschedulesForFrom = flightschedulesForFrom;
	}

}
