package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AirportGeo generated by hbm2java
 */
@Entity
@Table(name = "airport_geo", catalog = "airportdb")
public class AirportGeo implements java.io.Serializable {

	private AirportGeoId id;

	public AirportGeo() {
	}

	public AirportGeo(AirportGeoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "airportId", column = @Column(name = "airport_id", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 50)),
			@AttributeOverride(name = "city", column = @Column(name = "city", length = 50)),
			@AttributeOverride(name = "country", column = @Column(name = "country", length = 50)),
			@AttributeOverride(name = "latitude", column = @Column(name = "latitude", nullable = false, precision = 11, scale = 8)),
			@AttributeOverride(name = "longitude", column = @Column(name = "longitude", nullable = false, precision = 11, scale = 8)),
			@AttributeOverride(name = "geolocation", column = @Column(name = "geolocation", nullable = false)) })
	public AirportGeoId getId() {
		return this.id;
	}

	public void setId(AirportGeoId id) {
		this.id = id;
	}

}
