package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.TypedQuery;
import javax.persistence.UniqueConstraint;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "airportdb", uniqueConstraints = @UniqueConstraint(columnNames = { "flight_id",
		"seat" }))
public class Booking implements java.io.Serializable {

	private Integer bookingId;
	private Flight flight;
	private Passenger passenger;
	private String seat;
	private BigDecimal price;

	public Booking() {
	}

	public Booking(Flight flight, Passenger passenger, BigDecimal price) {
		this.flight = flight;
		this.passenger = passenger;
		this.price = price;
	}

	public Booking(Flight flight, Passenger passenger, String seat, BigDecimal price) {
		this.flight = flight;
		this.passenger = passenger;
		this.seat = seat;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "booking_id", unique = true, nullable = false)
	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flight_id", nullable = false)
	public Flight getFlight() {
		return this.flight;
	}

	public void setFlight(Flight flight) {
		this.flight = flight;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "passenger_id", nullable = false)
	public Passenger getPassenger() {
		return this.passenger;
	}

	public void setPassenger(Passenger passenger) {
		this.passenger = passenger;
	}

	@Column(name = "seat", length = 4)
	public String getSeat() {
		return this.seat;
	}

	public void setSeat(String seat) {
		this.seat = seat;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	
	/*Custom Queries*/

	public static List<Booking> getAllBookingsInIdRange(EntityManager em) {
		TypedQuery<Booking> query = em.createQuery("SELECT b FROM Booking b WHERE b.bookingId > 100 AND b.bookingId < 1000", Booking.class);
		return query.getResultList();
	}
	
	
	
	
	
}
