package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FlightLogId generated by hbm2java
 */
@Embeddable
public class FlightLogId implements java.io.Serializable {

	private Date logDate;
	private String user;
	private int flightId;
	private String flightnoOld;
	private String flightnoNew;
	private short fromOld;
	private short toOld;
	private short fromNew;
	private short toNew;
	private Date departureOld;
	private Date arrivalOld;
	private Date departureNew;
	private Date arrivalNew;
	private int airplaneIdOld;
	private int airplaneIdNew;
	private short airlineIdOld;
	private short airlineIdNew;
	private String comment;

	public FlightLogId() {
	}

	public FlightLogId(Date logDate, String user, int flightId, String flightnoOld, String flightnoNew, short fromOld,
			short toOld, short fromNew, short toNew, Date departureOld, Date arrivalOld, Date departureNew,
			Date arrivalNew, int airplaneIdOld, int airplaneIdNew, short airlineIdOld, short airlineIdNew) {
		this.logDate = logDate;
		this.user = user;
		this.flightId = flightId;
		this.flightnoOld = flightnoOld;
		this.flightnoNew = flightnoNew;
		this.fromOld = fromOld;
		this.toOld = toOld;
		this.fromNew = fromNew;
		this.toNew = toNew;
		this.departureOld = departureOld;
		this.arrivalOld = arrivalOld;
		this.departureNew = departureNew;
		this.arrivalNew = arrivalNew;
		this.airplaneIdOld = airplaneIdOld;
		this.airplaneIdNew = airplaneIdNew;
		this.airlineIdOld = airlineIdOld;
		this.airlineIdNew = airlineIdNew;
	}

	public FlightLogId(Date logDate, String user, int flightId, String flightnoOld, String flightnoNew, short fromOld,
			short toOld, short fromNew, short toNew, Date departureOld, Date arrivalOld, Date departureNew,
			Date arrivalNew, int airplaneIdOld, int airplaneIdNew, short airlineIdOld, short airlineIdNew,
			String comment) {
		this.logDate = logDate;
		this.user = user;
		this.flightId = flightId;
		this.flightnoOld = flightnoOld;
		this.flightnoNew = flightnoNew;
		this.fromOld = fromOld;
		this.toOld = toOld;
		this.fromNew = fromNew;
		this.toNew = toNew;
		this.departureOld = departureOld;
		this.arrivalOld = arrivalOld;
		this.departureNew = departureNew;
		this.arrivalNew = arrivalNew;
		this.airplaneIdOld = airplaneIdOld;
		this.airplaneIdNew = airplaneIdNew;
		this.airlineIdOld = airlineIdOld;
		this.airlineIdNew = airlineIdNew;
		this.comment = comment;
	}

	@Column(name = "log_date", nullable = false, length = 26)
	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	@Column(name = "user", nullable = false, length = 100)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "flight_id", nullable = false)
	public int getFlightId() {
		return this.flightId;
	}

	public void setFlightId(int flightId) {
		this.flightId = flightId;
	}

	@Column(name = "flightno_old", nullable = false, length = 8)
	public String getFlightnoOld() {
		return this.flightnoOld;
	}

	public void setFlightnoOld(String flightnoOld) {
		this.flightnoOld = flightnoOld;
	}

	@Column(name = "flightno_new", nullable = false, length = 8)
	public String getFlightnoNew() {
		return this.flightnoNew;
	}

	public void setFlightnoNew(String flightnoNew) {
		this.flightnoNew = flightnoNew;
	}

	@Column(name = "from_old", nullable = false)
	public short getFromOld() {
		return this.fromOld;
	}

	public void setFromOld(short fromOld) {
		this.fromOld = fromOld;
	}

	@Column(name = "to_old", nullable = false)
	public short getToOld() {
		return this.toOld;
	}

	public void setToOld(short toOld) {
		this.toOld = toOld;
	}

	@Column(name = "from_new", nullable = false)
	public short getFromNew() {
		return this.fromNew;
	}

	public void setFromNew(short fromNew) {
		this.fromNew = fromNew;
	}

	@Column(name = "to_new", nullable = false)
	public short getToNew() {
		return this.toNew;
	}

	public void setToNew(short toNew) {
		this.toNew = toNew;
	}

	@Column(name = "departure_old", nullable = false, length = 26)
	public Date getDepartureOld() {
		return this.departureOld;
	}

	public void setDepartureOld(Date departureOld) {
		this.departureOld = departureOld;
	}

	@Column(name = "arrival_old", nullable = false, length = 26)
	public Date getArrivalOld() {
		return this.arrivalOld;
	}

	public void setArrivalOld(Date arrivalOld) {
		this.arrivalOld = arrivalOld;
	}

	@Column(name = "departure_new", nullable = false, length = 26)
	public Date getDepartureNew() {
		return this.departureNew;
	}

	public void setDepartureNew(Date departureNew) {
		this.departureNew = departureNew;
	}

	@Column(name = "arrival_new", nullable = false, length = 26)
	public Date getArrivalNew() {
		return this.arrivalNew;
	}

	public void setArrivalNew(Date arrivalNew) {
		this.arrivalNew = arrivalNew;
	}

	@Column(name = "airplane_id_old", nullable = false)
	public int getAirplaneIdOld() {
		return this.airplaneIdOld;
	}

	public void setAirplaneIdOld(int airplaneIdOld) {
		this.airplaneIdOld = airplaneIdOld;
	}

	@Column(name = "airplane_id_new", nullable = false)
	public int getAirplaneIdNew() {
		return this.airplaneIdNew;
	}

	public void setAirplaneIdNew(int airplaneIdNew) {
		this.airplaneIdNew = airplaneIdNew;
	}

	@Column(name = "airline_id_old", nullable = false)
	public short getAirlineIdOld() {
		return this.airlineIdOld;
	}

	public void setAirlineIdOld(short airlineIdOld) {
		this.airlineIdOld = airlineIdOld;
	}

	@Column(name = "airline_id_new", nullable = false)
	public short getAirlineIdNew() {
		return this.airlineIdNew;
	}

	public void setAirlineIdNew(short airlineIdNew) {
		this.airlineIdNew = airlineIdNew;
	}

	@Column(name = "comment", length = 200)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlightLogId))
			return false;
		FlightLogId castOther = (FlightLogId) other;

		return ((this.getLogDate() == castOther.getLogDate()) || (this.getLogDate() != null
				&& castOther.getLogDate() != null && this.getLogDate().equals(castOther.getLogDate())))
				&& ((this.getUser() == castOther.getUser()) || (this.getUser() != null && castOther.getUser() != null
						&& this.getUser().equals(castOther.getUser())))
				&& (this.getFlightId() == castOther.getFlightId())
				&& ((this.getFlightnoOld() == castOther.getFlightnoOld())
						|| (this.getFlightnoOld() != null && castOther.getFlightnoOld() != null
								&& this.getFlightnoOld().equals(castOther.getFlightnoOld())))
				&& ((this.getFlightnoNew() == castOther.getFlightnoNew())
						|| (this.getFlightnoNew() != null && castOther.getFlightnoNew() != null
								&& this.getFlightnoNew().equals(castOther.getFlightnoNew())))
				&& (this.getFromOld() == castOther.getFromOld()) && (this.getToOld() == castOther.getToOld())
				&& (this.getFromNew() == castOther.getFromNew()) && (this.getToNew() == castOther.getToNew())
				&& ((this.getDepartureOld() == castOther.getDepartureOld())
						|| (this.getDepartureOld() != null && castOther.getDepartureOld() != null
								&& this.getDepartureOld().equals(castOther.getDepartureOld())))
				&& ((this.getArrivalOld() == castOther.getArrivalOld()) || (this.getArrivalOld() != null
						&& castOther.getArrivalOld() != null && this.getArrivalOld().equals(castOther.getArrivalOld())))
				&& ((this.getDepartureNew() == castOther.getDepartureNew())
						|| (this.getDepartureNew() != null && castOther.getDepartureNew() != null
								&& this.getDepartureNew().equals(castOther.getDepartureNew())))
				&& ((this.getArrivalNew() == castOther.getArrivalNew()) || (this.getArrivalNew() != null
						&& castOther.getArrivalNew() != null && this.getArrivalNew().equals(castOther.getArrivalNew())))
				&& (this.getAirplaneIdOld() == castOther.getAirplaneIdOld())
				&& (this.getAirplaneIdNew() == castOther.getAirplaneIdNew())
				&& (this.getAirlineIdOld() == castOther.getAirlineIdOld())
				&& (this.getAirlineIdNew() == castOther.getAirlineIdNew())
				&& ((this.getComment() == castOther.getComment()) || (this.getComment() != null
						&& castOther.getComment() != null && this.getComment().equals(castOther.getComment())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLogDate() == null ? 0 : this.getLogDate().hashCode());
		result = 37 * result + (getUser() == null ? 0 : this.getUser().hashCode());
		result = 37 * result + this.getFlightId();
		result = 37 * result + (getFlightnoOld() == null ? 0 : this.getFlightnoOld().hashCode());
		result = 37 * result + (getFlightnoNew() == null ? 0 : this.getFlightnoNew().hashCode());
		result = 37 * result + this.getFromOld();
		result = 37 * result + this.getToOld();
		result = 37 * result + this.getFromNew();
		result = 37 * result + this.getToNew();
		result = 37 * result + (getDepartureOld() == null ? 0 : this.getDepartureOld().hashCode());
		result = 37 * result + (getArrivalOld() == null ? 0 : this.getArrivalOld().hashCode());
		result = 37 * result + (getDepartureNew() == null ? 0 : this.getDepartureNew().hashCode());
		result = 37 * result + (getArrivalNew() == null ? 0 : this.getArrivalNew().hashCode());
		result = 37 * result + this.getAirplaneIdOld();
		result = 37 * result + this.getAirplaneIdNew();
		result = 37 * result + this.getAirlineIdOld();
		result = 37 * result + this.getAirlineIdNew();
		result = 37 * result + (getComment() == null ? 0 : this.getComment().hashCode());
		return result;
	}

}
