package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FlightLog generated by hbm2java
 */
@Entity
@Table(name = "flight_log", catalog = "airportdb")
public class FlightLog implements java.io.Serializable {

	private FlightLogId id;

	public FlightLog() {
	}

	public FlightLog(FlightLogId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "logDate", column = @Column(name = "log_date", nullable = false, length = 26)),
			@AttributeOverride(name = "user", column = @Column(name = "user", nullable = false, length = 100)),
			@AttributeOverride(name = "flightId", column = @Column(name = "flight_id", nullable = false)),
			@AttributeOverride(name = "flightnoOld", column = @Column(name = "flightno_old", nullable = false, length = 8)),
			@AttributeOverride(name = "flightnoNew", column = @Column(name = "flightno_new", nullable = false, length = 8)),
			@AttributeOverride(name = "fromOld", column = @Column(name = "from_old", nullable = false)),
			@AttributeOverride(name = "toOld", column = @Column(name = "to_old", nullable = false)),
			@AttributeOverride(name = "fromNew", column = @Column(name = "from_new", nullable = false)),
			@AttributeOverride(name = "toNew", column = @Column(name = "to_new", nullable = false)),
			@AttributeOverride(name = "departureOld", column = @Column(name = "departure_old", nullable = false, length = 26)),
			@AttributeOverride(name = "arrivalOld", column = @Column(name = "arrival_old", nullable = false, length = 26)),
			@AttributeOverride(name = "departureNew", column = @Column(name = "departure_new", nullable = false, length = 26)),
			@AttributeOverride(name = "arrivalNew", column = @Column(name = "arrival_new", nullable = false, length = 26)),
			@AttributeOverride(name = "airplaneIdOld", column = @Column(name = "airplane_id_old", nullable = false)),
			@AttributeOverride(name = "airplaneIdNew", column = @Column(name = "airplane_id_new", nullable = false)),
			@AttributeOverride(name = "airlineIdOld", column = @Column(name = "airline_id_old", nullable = false)),
			@AttributeOverride(name = "airlineIdNew", column = @Column(name = "airline_id_new", nullable = false)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment", length = 200)) })
	public FlightLogId getId() {
		return this.id;
	}

	public void setId(FlightLogId id) {
		this.id = id;
	}

}
