package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Flightschedule generated by hbm2java
 */
@Entity
@Table(name = "flightschedule", catalog = "airportdb")
public class Flightschedule implements java.io.Serializable {

	private String flightno;
	private Airline airline;
	private Airport airportByTo;
	private Airport airportByFrom;
	private Date departure;
	private Date arrival;
	private Boolean monday;
	private Boolean tuesday;
	private Boolean wednesday;
	private Boolean thursday;
	private Boolean friday;
	private Boolean saturday;
	private Boolean sunday;

	public Flightschedule() {
	}

	public Flightschedule(String flightno, Airline airline, Airport airportByTo, Airport airportByFrom, Date departure,
			Date arrival) {
		this.flightno = flightno;
		this.airline = airline;
		this.airportByTo = airportByTo;
		this.airportByFrom = airportByFrom;
		this.departure = departure;
		this.arrival = arrival;
	}

	public Flightschedule(String flightno, Airline airline, Airport airportByTo, Airport airportByFrom, Date departure,
			Date arrival, Boolean monday, Boolean tuesday, Boolean wednesday, Boolean thursday, Boolean friday,
			Boolean saturday, Boolean sunday) {
		this.flightno = flightno;
		this.airline = airline;
		this.airportByTo = airportByTo;
		this.airportByFrom = airportByFrom;
		this.departure = departure;
		this.arrival = arrival;
		this.monday = monday;
		this.tuesday = tuesday;
		this.wednesday = wednesday;
		this.thursday = thursday;
		this.friday = friday;
		this.saturday = saturday;
		this.sunday = sunday;
	}

	@Id

	@Column(name = "flightno", unique = true, nullable = false, length = 8)
	public String getFlightno() {
		return this.flightno;
	}

	public void setFlightno(String flightno) {
		this.flightno = flightno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "airline_id", nullable = false)
	public Airline getAirline() {
		return this.airline;
	}

	public void setAirline(Airline airline) {
		this.airline = airline;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "to", nullable = false)
	public Airport getAirportByTo() {
		return this.airportByTo;
	}

	public void setAirportByTo(Airport airportByTo) {
		this.airportByTo = airportByTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "from", nullable = false)
	public Airport getAirportByFrom() {
		return this.airportByFrom;
	}

	public void setAirportByFrom(Airport airportByFrom) {
		this.airportByFrom = airportByFrom;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "departure", nullable = false, length = 16)
	public Date getDeparture() {
		return this.departure;
	}

	public void setDeparture(Date departure) {
		this.departure = departure;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "arrival", nullable = false, length = 16)
	public Date getArrival() {
		return this.arrival;
	}

	public void setArrival(Date arrival) {
		this.arrival = arrival;
	}

	@Column(name = "monday")
	public Boolean getMonday() {
		return this.monday;
	}

	public void setMonday(Boolean monday) {
		this.monday = monday;
	}

	@Column(name = "tuesday")
	public Boolean getTuesday() {
		return this.tuesday;
	}

	public void setTuesday(Boolean tuesday) {
		this.tuesday = tuesday;
	}

	@Column(name = "wednesday")
	public Boolean getWednesday() {
		return this.wednesday;
	}

	public void setWednesday(Boolean wednesday) {
		this.wednesday = wednesday;
	}

	@Column(name = "thursday")
	public Boolean getThursday() {
		return this.thursday;
	}

	public void setThursday(Boolean thursday) {
		this.thursday = thursday;
	}

	@Column(name = "friday")
	public Boolean getFriday() {
		return this.friday;
	}

	public void setFriday(Boolean friday) {
		this.friday = friday;
	}

	@Column(name = "saturday")
	public Boolean getSaturday() {
		return this.saturday;
	}

	public void setSaturday(Boolean saturday) {
		this.saturday = saturday;
	}

	@Column(name = "sunday")
	public Boolean getSunday() {
		return this.sunday;
	}

	public void setSunday(Boolean sunday) {
		this.sunday = sunday;
	}

}
