package at.qe.sepm.skeleton.model;
// Generated Feb 20, 2019, 7:50:55 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Passenger generated by hbm2java
 */
@Entity
@Table(name = "passenger", catalog = "airportdb", uniqueConstraints = @UniqueConstraint(columnNames = "passportno"))
public class Passenger implements java.io.Serializable {

	private Integer passengerId;
	private String passportno;
	private String firstname;
	private String lastname;
	private Passengerdetails passengerdetails;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Passenger() {
	}

	public Passenger(String passportno, String firstname, String lastname) {
		this.passportno = passportno;
		this.firstname = firstname;
		this.lastname = lastname;
	}

	public Passenger(String passportno, String firstname, String lastname, Passengerdetails passengerdetails,
			Set<Booking> bookings) {
		this.passportno = passportno;
		this.firstname = firstname;
		this.lastname = lastname;
		this.passengerdetails = passengerdetails;
		this.bookings = bookings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "passenger_id", unique = true, nullable = false)
	public Integer getPassengerId() {
		return this.passengerId;
	}

	public void setPassengerId(Integer passengerId) {
		this.passengerId = passengerId;
	}

	@Column(name = "passportno", unique = true, nullable = false, length = 9)
	public String getPassportno() {
		return this.passportno;
	}

	public void setPassportno(String passportno) {
		this.passportno = passportno;
	}

	@Column(name = "firstname", nullable = false, length = 100)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 100)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "passenger")
	public Passengerdetails getPassengerdetails() {
		return this.passengerdetails;
	}

	public void setPassengerdetails(Passengerdetails passengerdetails) {
		this.passengerdetails = passengerdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passenger")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
